{
  try {
    callback((T)caller);
  }
 catch (  Throwable ex) {
    completeExceptionally(ex);
  }
}
